### ISSUE TITLE
文章没有删除，查看评论说，文章删除了

### ISSUE THREAD

**Issue by hqzhen** [langhsu/mblog#36]
![image](https://user-images.githubusercontent.com/45785181/81048251-91574e00-8eee-11ea-8081-b464ee6eea24.png)

**Comment by hqzhen** [comment]
改了这里就能出来，不知道有没有其他影响
![image](https://user-images.githubusercontent.com/45785181/81051021-98cd2600-8ef3-11ea-8db0-b6b5f0acecd9.png)

**Comment by langhsu** [comment]
感谢反馈，这是一个bug 已修复
